name: Cowsays Workflow

on:
    workflow_dispatch:
        inputs:
            message:
                description: 'What do you want the cow to say?'
                required: true
                default: 'Moo!'

jobs:
    cowsay:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code 
              uses: actions/checkout@v4
            - name: Check Branch Name
              uses: chidubesteve/branchCheck@v1.1
              with:
                allowed_branch: "master" # Change this to the branch you want to allow
            - name: Cowsay
              uses: mscoutermarsh/cowsays-action@master
              with:
               text: "${{ github.event.inputs.message }}"
               color: "green"