name: TASK - Pass data

on:
  workflow_dispatch:
    inputs:
      math_number:
        description: 'Your starting value (any number)'
        required: true
        type: number
        default: 3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate the math answer
        id: math_answer
        shell: bash
        # I need to implement this `Change the lines with the comment `#TODO edit here` so that:
#• The first step (id: math_answer) saves the answer to the outputs
#• The second step reads the saved value and prints it out (echo)` but i don't know how to and what this values/variables means
        run: |
          exm="example, you can remove me"
          ans=$((${{ github.event.inputs.math_number }} + 10))
          echo "You need to pass this value: $ans"
          echo "EXAMPLE=$exm" >> "$GITHUB_OUTPUT"
          echo "ANSWER=$ans" >> "$GITHUB_OUTPUT" 

      - name: Show the answer
        run: |
          echo "The Answer to the maths result is:"
          echo "The answers is: ${{steps.math_answer.outputs.ANSWER}}"



